version: '2.0'
services:
  consul:
    image: consul:1.6.2
    hostname: "consul"
    networks:
      - host
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    command: "agent -server -bootstrap-expect 1 -ui -client 0.0.0.0"

  vault:
    image: vault:1.3.0
    container_name: vault
    ports:
      - "9200:8200"
    volumes:
      - ./vault.json:/config.json
    hostname: "vault"
    networks:
      - host
    cap_add:
      - IPC_LOCK
    command: >-
      server
      -config=/config.json

  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
      - IPC_LOCK
    networks:
      - host
    hostname: "client"
    environment:
      - VAULT_TOKEN=root_token
      - CONSUL_HTTP_ADDR=consul_ip:8500
      - VAULT_ADDR=http://vault_ip:8200
    command: "tail -f /dev/null"

networks:
  host:
