version: '2.0'
services:
  consul:
    image: consul:1.6.2
    hostname: "consul"
    networks:
      - vault
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    command: "agent -server -bootstrap-expect 1 -ui  -client 0.0.0.0"

  vault:
    image: vault:1.3.0
    container_name: vault
    ports:
      - "9200:8200"
    volumes:
      - ./vault.json:/config.json
    hostname: "vault2"
    networks:
      - vault
    cap_add:
      - IPC_LOCK
    command: "server -config=/config.json"

  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CONSUL_HTTP_ADDR=host.docker.internal:8500
      - VAULT_ADDR=http://host.docker.internal:9200
    command: tail -f /dev/null

networks:
  vault: