version: '3.6'

services:

  server-bootstrap:
    image: consul:1.2.1
    ports:
      - 8500:8500
    command: "agent -server -bootstrap -ui -client 0.0.0.0 -bind '{{ GetInterfaceIP \"eth0\" }}'"

  server:
    image: consul:1.2.1
    command: "agent -server -retry-join server-bootstrap -client 0.0.0.0 -bind '{{ GetInterfaceIP \"eth0\" }}'"
    deploy:
      replicas: 2
    depends_on:
      - server-bootstrap

  client:
    image: consul:1.2.1
    command: "agent -retry-join server-bootstrap -client 0.0.0.0 -bind '{{ GetInterfaceIP \"eth0\" }}'"
    deploy:
      replicas: 2
    depends_on:
      - server-bootstrap

  vault:
    depends_on:
      - consul
    image: vault
    container_name: "vault"
    hostname: "vault"
    restart: always
    cap_add:
      - IPC_LOCK
    ports:
      - 8200:8200
    environment:
      VAULT_LOCAL_CONFIG: '{"backend": {"consul": {"address": "http://server-bootstrap:8500", "path": "vault"}}, "listener": {"tcp": {"address": "0.0.0.0:8200", "tls_disable": "1"}}, "default_lease_ttl": "24h", "ui":true, "max_lease_ttl": "720h", "disable_mlock":true}'
      VAULT_ADDR: "http://0.0.0.0:8200"
    command:
      - server
    ulimits:
      nproc: 65535
    cap_add:
      - ALL
    privileged: true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  default:
    external:
      name: host